# Setup
title:            DATA PLAYBOOK
tagline:          'Social Interest Solutions'
description:      'SIS Data Playbook'
url:              'https://social-interest-solutions.github.io/dataplaybook'
baseurl:          'https://social-interest-solutions.github.io/dataplaybook'

author:
  name:           'Social Interest Solutions'
  url:            https://twitter.com/SISOrg

# Custom vars
version:          0.1 | May 2019

github:
  repo:           https://github.com/Social-Interest-Solutions/DataPlaybook
